#
# Gradle
#
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.tooling.parallel=true

#
# Android
#
android.useAndroidX=true
android.nonTransitiveRClass=true

#
# Kotlin
#
kotlin.code.style=official
